### ISSUE TITLE
Schema identifier 404

### ISSUE THREAD

**Issue by moradology** [stac-extensions/single-file-stac#2]
Unfortunately, the [canonical schema location](https://stac-extensions.github.io/single-file-stac/v1.0.0/schema.json) is currently a 404. This would be less of an issue if the schema, itself, did not [mandate](https://github.com/stac-extensions/single-file-stac/blob/main/json-schema/schema.json#L22-L30) that this specific URL be contained within `stac_extensions`. As it now stands, the `single-file-stac` extension appears to be either unusable or impossible to fully validate

**Comment by m-mohr** [comment]
I think this extension got deprecated, right @matthewhanson ?

**Comment by matthewhanson** [comment]
Well, the `single-file-stac` needs to be rethought I think., An ItemCollection is not a STAC object so validation of it with an extension doesn't make any sense.  

I like the ability to save a single file and have it contain both Items and Collections. Maybe it still is an extension to STAC, but it's not an extension that can be validated with a schema with any of the tools now because they won't recognize a "FeatureCollection" type as anything valid...and there's no 'stac_extensions' field or 'stac_version' here.
